// All user-facing text lives here. Edit wording in this file only.
// Option ids are stored in the browser, so change a label freely but
// avoid renaming an id once parents are using the tool.
// The Chinese version lives in content-zh.js with the same shape.

(function () {
const opt = (id, label) => ({ id, label });

const en = {
  brand: {
    name: 'EF TakeOff Coaching',
    site: 'https://eftakeoffcoachingcg.com/',
    siteLabel: 'eftakeoffcoachingcg.com',
    app: 'Parent-Teacher Conference Companion',
    logoAlt: 'EF TakeOff Coaching 卓行咨询',
  },

  lang: { code: 'en', locale: 'en', switchTo: 'zh', switchLabel: '中文', switchAria: '切换到中文 (Switch to Chinese)' },

  ui: {
    next: 'Next',
    back: 'Back',
    saveLater: 'Save & Come Back Later',
    saved: 'Saved on this device',
    saveFailed: "Couldn't save in this browser. Your answers will last until you close this tab.",
    savedFlash: "Your answers are saved in this browser. Come back anytime on this device and pick up where you left off. To continue on another device, download a backup file from the Snapshot page.",
    optional: 'Optional',
    otherLabel: 'Anything else? (optional)',
    notRecorded: 'Not recorded',
    resetConfirm: 'This will clear all answers saved in this browser. Continue?',
    resetDone: 'Everything was cleared.',
    undo: 'Undo',
    restored: 'Your answers are back.',
    pastDate: "This date has already passed. That's fine if you're filling this in afterward.",
    skipHint: 'Everything here is optional. Skip anything that doesn’t fit.',
    skipAhead: 'Skip ahead to:',
    colon: ': ',
    nextTo: (t) => `Next: ${t}`,
    partLabel: (k) => `Part ${k}: `,
    chosenBadge: (n) => `${n} chosen`,
    rowLabel: (col, i) => `${col}, row ${i}`,
    removeRowLabel: (i) => `Remove row ${i}`,
    progress: 'Progress',
    partsNav: 'Parts of this stage',
    emailTruncated: '[…] The full summary was copied to your clipboard. Paste it here to include everything.',
    addToCalendar: 'Add to calendar',
    skipLink: 'Skip to main content',
    install: 'Install app',
    installDone: 'Installed. You’ll find “Conference Prep” on your home screen or apps list.',
    iosTipTitle: 'Keep this on your phone.',
    iosTip: 'In Safari, tap the Share button, then “Add to Home Screen”. It will work like an app, even offline.',
    wechatTipTitle: 'Want to keep this on your phone?',
    wechatTip: 'Tap ··· at the top right and choose “Open in browser”, then add it to your home screen from there.',
    tipDismiss: 'Got it',
    noscript: 'This tool needs JavaScript turned on to work.',
    footerPrivacy: 'Your answers are stored only in this browser. Nothing is sent anywhere.',
    connect: 'Connect with EF TakeOff Coaching',
    qrOfficial: 'WeChat Official Account',
    qrWechat: 'WeChat: CourtGum',
    qrOfficialAlt: 'QR code for the EF TakeOff Coaching WeChat Official Account',
    qrWechatAlt: 'QR code to add Courtney on WeChat (CourtGum)',
  },

  stages: [
    { id: 'before', short: 'Before', title: 'Before the Conference', route: 'before/1' },
    { id: 'questions', short: 'Questions', title: 'Questions to Ask', route: 'questions' },
    { id: 'during', short: 'During', title: 'During the Conference', route: 'during' },
    { id: 'after', short: 'After', title: 'After the Conference', route: 'after' },
    { id: 'snapshot', short: 'Snapshot', title: 'Conference Snapshot', route: 'snapshot' },
  ],

  landing: {
    eyebrow: 'Parent-Teacher Conference Companion',
    title: 'Go Into the Conference With a Plan',
    sub: 'A simple tool to help you organize what you’ve noticed, recognize your child’s strengths, and have a more productive conversation with their teacher.',
    start: 'Start Preparing',
    how: 'How this works',
    explain: 'You don’t need to diagnose the problem before you talk with the school. Start with what you’re noticing, when it happens, what helps, and what you’d like to understand better.',
    steps: [
      { title: 'Before the conference', body: 'Note your child’s strengths, what you’re noticing, when it happens, and what has been tried. About 10 minutes.' },
      { title: 'Questions to ask', body: 'Pick up to 8 questions that open the conversation. Add your own.' },
      { title: 'During the conference', body: 'Take simple notes, tick off questions, and use the prompts if the conversation gets stuck.' },
      { title: 'After the conference', body: 'Choose what matters most, decide what to try, and get a one-page Conference Snapshot to print or save.' },
    ],
    privacy: 'Your answers stay in this browser on this device. There’s no account, and nothing is sent anywhere. On a shared computer, use “Start over” when you’re finished.',
    skipTitle: 'Meeting coming up soon? Jump straight to what you need.',
    welcomeBack: 'Welcome back',
    welcomeBody: 'Your answers are saved on this device.',
    continue: 'Continue where you left off',
    reset: 'Start over',
    importPrompt: 'Have a backup file from another device?',
    importButton: 'Open a backup file',
    disclaimer: 'This tool is for educational and communication purposes. It is not a diagnostic assessment or a substitute for professional evaluation.',
  },

  before: {
    eyebrow: 'Stage 1 · Before the Conference',
    title: 'Let’s Get Clear on What You’re Seeing',
    intro: 'You don’t need to figure out “what’s wrong.” Focus on what you see, when you see it, and what seems to make things easier or harder.',
    parts: [
      { key: 'A', title: 'Your child’s strengths' },
      { key: 'B', title: 'What you’re noticing' },
      { key: 'C', title: 'When it happens' },
      { key: 'D', title: 'What’s been tried' },
      { key: 'E', title: 'What your child says' },
    ],

    strengthsQ: 'What does your child do well?',
    strengthsHint: 'Choose as many as fit.',
    strengths: [
      opt('curious', 'Curious'),
      opt('creative', 'Creative'),
      opt('funny', 'Funny'),
      opt('kind', 'Kind'),
      opt('persistent', 'Persistent'),
      opt('verbal', 'Strong verbal skills'),
      opt('people', 'Good with people'),
      opt('memory', 'Strong memory'),
      opt('problem-solver', 'Good problem solver'),
      opt('hands-on', 'Hands-on learner'),
      opt('passionate', 'Passionate about specific interests'),
      opt('independent', 'Independent in some areas'),
      opt('other', 'Other'),
    ],
    engagedQ: 'What does your child enjoy or become deeply engaged in?',
    engagedHint: 'Interests, activities, times they lose track of time.',

    noticingQ: 'What concerns or patterns have you noticed recently?',
    noticingHint: 'These are things you may be noticing. Choose any that fit, or none.',
    noticing: [
      opt('forget-homework', 'Forgetting homework or materials'),
      opt('getting-started', 'Difficulty getting started'),
      opt('finishing', 'Difficulty finishing work'),
      opt('losing-things', 'Losing things'),
      opt('multi-step', 'Difficulty following multi-step directions'),
      opt('organizing', 'Trouble organizing materials'),
      opt('time', 'Difficulty managing time'),
      opt('distracted', 'Frequently distracted'),
      opt('overwhelmed', 'Appears overwhelmed by schoolwork'),
      opt('avoids', 'Avoids certain tasks'),
      opt('emotional', 'Becomes very emotional around schoolwork'),
      opt('transitions', 'Difficulty transitioning between activities'),
      opt('sitting', 'Trouble sitting through longer tasks'),
      opt('takes-longer', 'Work takes much longer than expected'),
      opt('inconsistent', 'Inconsistent performance'),
      opt('studying', 'Trouble studying independently'),
      opt('asking-help', 'Difficulty communicating when help is needed'),
      opt('other', 'Other'),
    ],

    whenQ: 'Where or when do you notice this most?',
    whenHint: 'Choose any that fit.',
    when: [
      opt('morning', 'Morning routine'),
      opt('homework', 'Homework'),
      opt('ready-school', 'Getting ready for school'),
      opt('subjects', 'Specific subjects'),
      opt('long-assignments', 'Long assignments'),
      opt('tests', 'Tests'),
      opt('projects', 'Projects'),
      opt('transitions', 'Transitions'),
      opt('group', 'Group work'),
      opt('independent', 'Independent work'),
      opt('after-school', 'After school'),
      opt('bedtime', 'Bedtime'),
      opt('many', 'Across many settings'),
      opt('other', 'Other'),
    ],
    notProblemQ: 'Are there situations where this is NOT a problem?',
    notProblemHint: 'Context matters. Knowing when things go well is as useful as knowing when they’re hard.',

    triedQ: 'What have you or the school already tried?',
    triedHint: 'Choose any that have been tried. You can say how each one went.',
    tried: [
      opt('visual-reminders', 'Visual reminders'),
      opt('checklists', 'Checklists'),
      opt('breaking-steps', 'Breaking assignments into steps'),
      opt('extra-reminders', 'Extra reminders'),
      opt('written-instructions', 'Written instructions'),
      opt('verbal-instructions', 'Verbal instructions'),
      opt('timers', 'Timers'),
      opt('org-systems', 'Organizational systems'),
      opt('extra-time', 'Extra time'),
      opt('seating', 'Seating changes'),
      opt('movement', 'Movement breaks'),
      opt('check-ins', 'One-to-one check-ins'),
      opt('parent-monitoring', 'Parent monitoring'),
      opt('rewards', 'Reward systems'),
      opt('other', 'Other'),
    ],
    helpQ: 'Did it seem to help?',
    helpSection: 'How did each one go?',
    ratings: [
      opt('lot', 'Helped a lot'),
      opt('somewhat', 'Helped somewhat'),
      opt('little', 'Didn’t make much difference'),
      opt('temporary', 'Worked temporarily'),
      opt('unsure', 'Not sure'),
    ],

    childQ: 'What does your child say about what’s happening?',
    childExamplesLabel: 'Things children often say',
    childExamples: [
      'I forgot.',
      'I didn’t know what I was supposed to do.',
      'It’s too much.',
      'I hate it.',
      'I understand it, I just don’t do it.',
      'The teacher thinks I’m lazy.',
      'I don’t know.',
    ],
    childNoteLabel: 'Why this matters',
    childNote: 'Your child’s explanation is important data. It may help you understand whether the barrier is skill, motivation, emotion, clarity, environment, or something else.',
  },

  questions: {
    eyebrow: 'Stage 2 · Questions to Ask',
    title: 'Questions That Open the Conversation',
    intro: 'The goal isn’t to convince the teacher that something is wrong. The goal is to understand what they’re seeing and work together to identify what might help.',
    max: 8,
    counter: (n) => `${n} ${n === 1 ? 'question' : 'questions'} selected`,
    counterOf: 'up to 8',
    fullNote: 'You’ve chosen 8, which is plenty for one conversation. Remove one if you’d like to swap in another.',
    listTitle: 'Your list',
    listEmpty: 'Questions you choose will appear here. Four to six is often enough.',
    remove: 'Remove',
    addLabel: 'Add your own question',
    addButton: 'Add',
    addDuplicate: 'That question is already on your list.',
    addFull: 'Your list has 8 questions. Remove one to add another.',
    addEmpty: 'Type a question first.',
    addDone: 'Added to your list.',
    categories: [
      {
        id: 'pattern', title: 'Understanding the pattern', items: [
          'When do you notice this most?',
          'Are there particular subjects or types of assignments where this happens?',
          'Does it happen during independent work, group work, or both?',
          'What does it look like from your perspective?',
          'Are there situations where you see the opposite pattern?',
        ],
      },
      {
        id: 'work', title: 'Understanding the work', items: [
          'Does my child understand the material?',
          'When they don’t complete something, do you have a sense of what gets in the way?',
          'Are they struggling with the content, the process of completing the work, or both?',
          'How much prompting do they typically need?',
        ],
      },
      {
        id: 'ef', title: 'Executive functioning: planning, starting & organizing', items: [
          'How does my child manage multi-step assignments?',
          'How independently do they get started?',
          'How do they manage deadlines?',
          'Do they keep track of materials?',
          'How do they respond when plans change?',
          'What happens when they become overwhelmed?',
        ],
      },
      {
        id: 'strengths', title: 'Strengths', items: [
          'When does my child seem most confident?',
          'What kinds of activities bring out their strengths?',
          'What do they respond well to?',
          'What have you noticed they can do independently?',
        ],
      },
      {
        id: 'supports', title: 'Supports', items: [
          'What have you already tried?',
          'What seems to help?',
          'What doesn’t seem to help?',
          'Is there a support we could try consistently for the next few weeks?',
          'How will we know whether it is helping?',
        ],
      },
    ],
  },

  during: {
    eyebrow: 'Stage 3 · During the Conference',
    title: 'During the Conversation',
    intro: 'Short notes are fine. You can tidy them up afterward.',
    myQuestions: 'Your questions',
    myQuestionsHint: 'Tick them off as you go. Anything left unticked goes into “Questions to revisit.”',
    noQuestions: 'You haven’t chosen any questions yet.',
    chooseQuestions: 'Choose questions',
    fields: [
      { id: 'teacherSeeing', label: 'What the teacher is seeing' },
      { id: 'teacherStrengths', label: 'Strengths the teacher mentioned' },
      { id: 'patterns', label: 'Patterns we discussed' },
      { id: 'supports', label: 'Supports that may help' },
      { id: 'agreed', label: 'What we agreed to try' },
    ],
    whoTitle: 'Who will do what?',
    cols: { action: 'Action', person: 'Person responsible', when: 'When?' },
    addRow: 'Add a row',
    removeRow: 'Remove row',
    checkBack: 'When will we check back?',
    pauseTitle: 'If the conversation gets stuck',
    pauseHint: 'Try one of these:',
    pausePrompts: [
      'Can you give me an example?',
      'What usually happens right before that?',
      'What does it look like when things are going well?',
      'What have you noticed helps?',
      'Could we try one small support and check back in?',
      'What would success look like?',
    ],
  },

  after: {
    eyebrow: 'Stage 4 · After the Conference',
    title: 'Turn the Conversation Into a Plan',
    learned: 'What did you learn?',
    prioritiesQ: 'What feels most important right now?',
    prioritiesHint: 'Choose up to 3.',
    prioritiesFull: 'You’ve chosen 3. Unselect one to pick something different.',
    maxPriorities: 3,
    priorities: [
      opt('understanding', 'Understanding the problem'),
      opt('overwhelm', 'Reducing overwhelm'),
      opt('organization', 'Improving organization'),
      opt('starting', 'Getting started more independently'),
      opt('completing', 'Completing work'),
      opt('transitions', 'Managing transitions'),
      opt('conflict', 'Reducing conflict around homework'),
      opt('confidence', 'Building confidence'),
      opt('communication', 'Improving communication with school'),
      opt('other', 'Other'),
    ],
    willTry: 'What are we going to try?',
    watchFor: 'What will we watch for?',
    watchForHint: 'Small signs that something is helping, or not.',
    reviewDate: 'When will we review progress?',
    toSnapshot: 'See my Conference Snapshot',
  },

  snapshot: {
    eyebrow: 'Conference Snapshot',
    title: 'Parent-Teacher Conference Snapshot',
    download: 'Download PDF',
    downloading: 'Preparing your PDF…',
    pdfDone: 'Your PDF has been downloaded.',
    pdfFailed: 'The PDF couldn’t be created here. It needs an internet connection the first time. You can use “Print” and choose “Save as PDF” instead.',
    print: 'Print',
    send: 'Send',
    sendTitle: 'Send or share',
    shareFile: 'Share PDF…',
    email: 'Email as text',
    copy: 'Copy as text',
    copied: 'Copied. You can paste it into an email, WeChat or a notes app.',
    copyFailed: 'Copying didn’t work in this browser. Try “Email as text” instead.',
    calendar: 'Add follow-up dates to calendar',
    edit: 'Edit answers',
    backupTitle: 'Keep or move your answers',
    backupHint: 'A backup file lets you continue on another device or browser. It includes your notes, so keep it private.',
    exportBtn: 'Download backup file',
    importBtn: 'Open a backup file',
    importOk: 'Your answers were loaded from the file.',
    importBad: 'That file isn’t a Conference Companion backup, so nothing was changed.',
    importConfirm: 'Replace the answers in this browser with the ones in this file?',
    checkBackEvent: 'Check back with teacher (conference follow-up)',
    reviewEvent: 'Review progress on our conference plan',
    analyticsLabel: 'Help improve this tool: share which checkbox options I chose, anonymously. Written notes and dates are never shared.',
    analyticsThanks: 'Thank you. Only anonymous checkbox choices are shared.',
    reset: 'Start over',
    prepared: 'Prepared',
    sections: {
      strengths: 'My child’s strengths',
      noticing: 'What we’re noticing',
      teacher: 'What the teacher is seeing',
      barriers: 'What seems to be getting in the way',
      supports: 'Supports that may help',
      trying: 'What we’re going to try',
      who: 'Who is responsible for what',
      followUp: 'Follow-up date',
      revisit: 'Questions to revisit',
    },
    labels: {
      engaged: 'Deeply engaged in',
      teacherStrengths: 'Strengths the teacher mentioned',
      when: 'Most noticeable during',
      notProblem: 'Not a problem when',
      patterns: 'Patterns we discussed',
      childSays: 'In my child’s words',
      limited: 'Tried, with limited or short-lived effect',
      learned: 'What I learned',
      helped: 'Already seems to help',
      agreed: 'Agreed in the meeting',
      plan: 'Our plan',
      priorities: 'Most important right now',
      watchFor: 'What we’ll watch for',
      checkBack: 'Check back with the teacher',
      review: 'Review progress',
    },
    rememberLabel: 'Remember',
    remember: 'The goal is not to solve everything in one meeting. A useful conference gives you a clearer picture, a small number of next steps, and a way to check whether those steps are helping.',
  },
};

window.PTCC = window.PTCC || {};
window.PTCC.content = window.PTCC.content || {};
window.PTCC.content.en = en;
})();
