// 简体中文版本。结构与 content.js 完全相同；选项 id 必须保持一致。
// Chinese (Simplified). Same shape and ids as content.js.
// Please have a native speaker review wording before publishing.

(function () {
const opt = (id, label) => ({ id, label });

const zh = {
  brand: {
    name: 'EF TakeOff Coaching 卓行咨询',
    site: 'https://eftakeoffcoachingcg.com/',
    siteLabel: 'eftakeoffcoachingcg.com',
    app: '家长会准备助手',
    logoAlt: 'EF TakeOff Coaching 卓行咨询',
  },

  lang: { code: 'zh', locale: 'zh-CN', switchTo: 'en', switchLabel: 'English', switchAria: 'Switch to English（切换到英文）' },

  ui: {
    next: '下一步',
    back: '返回',
    saveLater: '保存，稍后继续',
    saved: '已保存在本设备',
    saveFailed: '此浏览器无法保存。关闭此页面前，您的内容仍然有效。',
    savedFlash: '您的内容已保存在此浏览器中。随时可以在这台设备上回来继续。如需换一台设备，请在「会谈摘要」页面下载备份文件。',
    optional: '选填',
    otherLabel: '还有其他吗？（选填）',
    notRecorded: '未填写',
    resetConfirm: '这将清除此浏览器中保存的所有内容。确定继续吗？',
    resetDone: '所有内容已清除。',
    undo: '撤销',
    restored: '您的内容已恢复。',
    pastDate: '这个日期已经过去了。如果您是在会后补填，这完全没问题。',
    skipHint: '以下内容都是选填的，不适用的可以直接跳过。',
    skipAhead: '直接跳到：',
    colon: '：',
    nextTo: (t) => `下一步：${t}`,
    partLabel: (k) => `第 ${k} 部分：`,
    chosenBadge: (n) => `已选 ${n} 个`,
    rowLabel: (col, i) => `${col}，第 ${i} 行`,
    removeRowLabel: (i) => `删除第 ${i} 行`,
    progress: '进度',
    partsNav: '本步骤的各部分',
    emailTruncated: '[…] 完整摘要已复制到剪贴板，请粘贴到这里以包含全部内容。',
    addToCalendar: '加入日历',
    skipLink: '跳到主要内容',
    install: '安装应用',
    installDone: '已安装。您可以在主屏幕或应用列表中找到「Conference Prep」。',
    iosTipTitle: '把它放到手机主屏幕。',
    iosTip: '在 Safari 中点击「分享」按钮，然后选择「添加到主屏幕」。之后可以像应用一样使用，离线也能打开。',
    wechatTipTitle: '想把它保存在手机上？',
    wechatTip: '点击右上角「···」，选择「在浏览器中打开」，然后在浏览器中添加到主屏幕。',
    tipDismiss: '知道了',
    showMe: '查看',
    close: '关闭',
    phoneTitle: '把它放到手机上',
    phoneIntro: '只需添加到主屏幕一次，之后就能像应用一样打开，没有网络也能使用。',
    phoneSteps: [
      { title: 'iPhone 或 iPad', body: '用 Safari 打开此页面，点击「分享」按钮，然后选择「添加到主屏幕」。' },
      { title: '安卓（Chrome 浏览器）', body: '点击右上角 ⋮ 菜单，选择「添加到主屏幕」。如果看到「安装」也可以使用；如果安装失败（在中国大陆较常见），请改选「创建快捷方式」，使用效果相同。' },
      { title: '华为、小米、OPPO、vivo 等自带浏览器', body: '打开浏览器菜单，选择「添加到桌面」或「添加到主屏幕」。' },
      { title: '在微信中打开的？', body: '点击右上角「···」，选择「在浏览器中打开」，然后按照上面的步骤操作。' },
    ],
    installHelp: '安装不成功？请查看首页的「把它放到手机上」。',
    noscript: '此工具需要开启 JavaScript 才能使用。',
    footerPrivacy: '您的内容只保存在此浏览器中，不会发送到任何地方。',
    connect: '关注 EF TakeOff Coaching 卓行咨询',
    qrOfficial: '微信公众号',
    qrWechat: '微信：CourtGum',
    qrOfficialAlt: 'EF TakeOff Coaching 微信公众号二维码',
    qrWechatAlt: '添加 Courtney 微信（CourtGum）的二维码',
  },

  stages: [
    { id: 'before', short: '会前', title: '会前准备', route: 'before/1' },
    { id: 'questions', short: '问题', title: '想问的问题', route: 'questions' },
    { id: 'during', short: '会中', title: '会谈进行中', route: 'during' },
    { id: 'after', short: '会后', title: '会后计划', route: 'after' },
    { id: 'snapshot', short: '摘要', title: '会谈摘要', route: 'snapshot' },
  ],

  landing: {
    eyebrow: '家长会准备助手',
    title: '带着计划走进家长会',
    sub: '一个简单的工具，帮助您整理观察到的情况、看见孩子的优势，并与老师进行更有成效的沟通。',
    start: '开始准备',
    how: '使用说明',
    explain: '和学校沟通之前，您不需要先找出「问题在哪里」。从您观察到的情况开始：什么时候发生、什么有帮助、以及您想进一步了解什么。',
    steps: [
      { title: '会前准备', body: '记录孩子的优势、您观察到的情况、发生的场景，以及已经尝试过的方法。大约 10 分钟。' },
      { title: '想问的问题', body: '挑选最多 8 个能打开话题的问题，也可以添加您自己的问题。' },
      { title: '会谈进行中', body: '简单记录要点，勾选已问过的问题；如果谈话卡住了，可以参考提示语。' },
      { title: '会后计划', body: '选出目前最重要的事，决定要尝试什么，并生成一页可打印或保存的会谈摘要。' },
    ],
    privacy: '您的内容只保存在这台设备的浏览器中。无需注册账户，也不会发送到任何地方。如果使用的是公用电脑，完成后请点击「重新开始」。',
    skipTitle: '家长会快到了？直接跳到您需要的部分。',
    welcomeBack: '欢迎回来',
    welcomeBody: '您的内容已保存在这台设备上。',
    continue: '从上次的位置继续',
    reset: '重新开始',
    importPrompt: '有从其他设备导出的备份文件吗？',
    importButton: '打开备份文件',
    disclaimer: '本工具仅用于学习与沟通，不是诊断评估，也不能替代专业评估。',
  },

  before: {
    eyebrow: '第一步 · 会前准备',
    title: '先看清楚您观察到的情况',
    intro: '您不需要弄清楚「哪里出了问题」。只需关注您看到了什么、在什么时候看到，以及什么会让事情变得更容易或更困难。',
    parts: [
      { key: 'A', title: '孩子的优势' },
      { key: 'B', title: '您观察到的情况' },
      { key: 'C', title: '发生的场景' },
      { key: 'D', title: '已经尝试过的方法' },
      { key: 'E', title: '孩子怎么说' },
    ],

    strengthsQ: '您的孩子擅长什么？',
    strengthsHint: '符合的都可以选。',
    strengths: [
      opt('curious', '好奇心强'),
      opt('creative', '有创造力'),
      opt('funny', '幽默风趣'),
      opt('kind', '善良'),
      opt('persistent', '有毅力'),
      opt('verbal', '语言表达能力强'),
      opt('people', '善于与人相处'),
      opt('memory', '记忆力好'),
      opt('problem-solver', '善于解决问题'),
      opt('hands-on', '喜欢动手学习'),
      opt('passionate', '对特定兴趣充满热情'),
      opt('independent', '在某些方面很独立'),
      opt('other', '其他'),
    ],
    engagedQ: '您的孩子喜欢什么，或者会全情投入在什么事情上？',
    engagedHint: '兴趣、活动，或让他们忘记时间的事情。',

    noticingQ: '最近您观察到了哪些情况或规律？',
    noticingHint: '以下是您可能观察到的一些情况。选择符合的即可，也可以都不选。',
    noticing: [
      opt('forget-homework', '忘记作业或学习用品'),
      opt('getting-started', '开始做事比较困难'),
      opt('finishing', '完成作业比较困难'),
      opt('losing-things', '经常丢东西'),
      opt('multi-step', '较难按照多步骤的指令完成任务'),
      opt('organizing', '整理学习用品比较困难'),
      opt('time', '时间管理比较困难'),
      opt('distracted', '容易分心'),
      opt('overwhelmed', '面对功课时显得不堪重负'),
      opt('avoids', '回避某些任务'),
      opt('emotional', '面对功课时情绪起伏较大'),
      opt('transitions', '在不同活动之间切换比较困难'),
      opt('sitting', '较难坚持完成较长的任务'),
      opt('takes-longer', '完成功课所需时间比预期长很多'),
      opt('inconsistent', '表现时好时坏'),
      opt('studying', '独立学习比较困难'),
      opt('asking-help', '需要帮助时较难说出来'),
      opt('other', '其他'),
    ],

    whenQ: '您最常在什么场景或时间观察到这些情况？',
    whenHint: '符合的都可以选。',
    when: [
      opt('morning', '早上的日常安排'),
      opt('homework', '做作业时'),
      opt('ready-school', '准备上学时'),
      opt('subjects', '特定科目'),
      opt('long-assignments', '较长的作业'),
      opt('tests', '考试'),
      opt('projects', '项目作业'),
      opt('transitions', '活动转换时'),
      opt('group', '小组活动'),
      opt('independent', '独立作业'),
      opt('after-school', '放学后'),
      opt('bedtime', '睡前'),
      opt('many', '在很多场景中都有'),
      opt('other', '其他'),
    ],
    notProblemQ: '有没有哪些情况下，这些都不是问题？',
    notProblemHint: '情境很重要。了解什么时候进展顺利，和了解什么时候比较困难同样有价值。',

    triedQ: '您或学校已经尝试过哪些方法？',
    triedHint: '选择已经尝试过的方法，然后可以说说每种方法的效果。',
    tried: [
      opt('visual-reminders', '视觉提示'),
      opt('checklists', '检查清单'),
      opt('breaking-steps', '把作业拆分成小步骤'),
      opt('extra-reminders', '额外提醒'),
      opt('written-instructions', '书面说明'),
      opt('verbal-instructions', '口头说明'),
      opt('timers', '计时器'),
      opt('org-systems', '整理收纳系统'),
      opt('extra-time', '延长时间'),
      opt('seating', '调整座位'),
      opt('movement', '活动休息'),
      opt('check-ins', '一对一沟通'),
      opt('parent-monitoring', '家长督促'),
      opt('rewards', '奖励机制'),
      opt('other', '其他'),
    ],
    helpQ: '效果如何？',
    helpSection: '每种方法的效果如何？',
    ratings: [
      opt('lot', '很有帮助'),
      opt('somewhat', '有些帮助'),
      opt('little', '变化不大'),
      opt('temporary', '短期有效'),
      opt('unsure', '不确定'),
    ],

    childQ: '孩子自己是怎么说的？',
    childExamplesLabel: '孩子们常说的话',
    childExamples: [
      '我忘了。',
      '我不知道要做什么。',
      '太多了。',
      '我讨厌这个。',
      '我懂，就是做不下去。',
      '老师觉得我很懒。',
      '我不知道。',
    ],
    childNoteLabel: '为什么这很重要',
    childNote: '孩子的解释是很重要的信息。它能帮助您了解，阻碍来自技能、动力、情绪、指令是否清楚、环境，还是其他因素。',
  },

  questions: {
    eyebrow: '第二步 · 想问的问题',
    title: '打开话题的问题',
    intro: '目的不是说服老师「孩子有问题」，而是了解老师看到的情况，并一起找出可能有帮助的方法。',
    max: 8,
    counter: (n) => `已选 ${n} 个问题`,
    counterOf: '最多 8 个',
    fullNote: '您已经选了 8 个问题，对一次谈话来说已经足够了。如果想换一个，可以先移除一个。',
    listTitle: '我的问题清单',
    listEmpty: '您选择的问题会显示在这里。一般 4 到 6 个就足够了。',
    remove: '移除',
    addLabel: '添加您自己的问题',
    addButton: '添加',
    addDuplicate: '这个问题已经在您的清单里了。',
    addFull: '您的清单已有 8 个问题。请先移除一个再添加。',
    addEmpty: '请先输入一个问题。',
    addDone: '已添加到您的清单。',
    categories: [
      {
        id: 'pattern', title: '了解规律', items: [
          '您最常在什么时候注意到这种情况？',
          '是否在某些科目或某类作业中特别明显？',
          '是在独立作业、小组活动，还是两者都有？',
          '从您的角度看，具体是什么样子的？',
          '有没有看到相反情况的时候？',
        ],
      },
      {
        id: 'work', title: '了解学习情况', items: [
          '我的孩子理解学习内容吗？',
          '当孩子没有完成某项任务时，您觉得是什么在阻碍他们？',
          '孩子的困难是在内容本身、完成作业的过程，还是两者都有？',
          '孩子通常需要多少提醒？',
        ],
      },
      {
        id: 'ef', title: '执行功能：计划、启动与整理', items: [
          '孩子如何应对多步骤的作业？',
          '孩子能多独立地开始一项任务？',
          '孩子如何管理截止日期？',
          '孩子能管理好自己的学习用品吗？',
          '计划有变化时，孩子会如何反应？',
          '孩子感到不堪重负时会怎样？',
        ],
      },
      {
        id: 'strengths', title: '优势', items: [
          '孩子在什么时候看起来最有自信？',
          '哪些活动最能展现孩子的优势？',
          '孩子对什么方式反应比较好？',
          '您注意到孩子能独立完成哪些事情？',
        ],
      },
      {
        id: 'supports', title: '支持方法', items: [
          '您已经尝试过哪些方法？',
          '什么方法似乎有帮助？',
          '什么方法似乎没有帮助？',
          '有没有一种支持方法，我们可以在接下来几周持续尝试？',
          '我们怎么知道这个方法是否有帮助？',
        ],
      },
    ],
  },

  during: {
    eyebrow: '第三步 · 会谈进行中',
    title: '谈话进行中',
    intro: '简短记录就好，会后可以再整理。',
    myQuestions: '我的问题',
    myQuestionsHint: '问过的可以勾选。没有勾选的问题会出现在「之后再跟进的问题」中。',
    noQuestions: '您还没有选择问题。',
    chooseQuestions: '去选择问题',
    fields: [
      { id: 'teacherSeeing', label: '老师看到的情况' },
      { id: 'teacherStrengths', label: '老师提到的优势' },
      { id: 'patterns', label: '我们讨论的规律' },
      { id: 'supports', label: '可能有帮助的支持方法' },
      { id: 'agreed', label: '我们约定尝试的方法' },
    ],
    whoTitle: '谁负责做什么？',
    cols: { action: '行动', person: '负责人', when: '时间' },
    addRow: '添加一行',
    removeRow: '删除这一行',
    checkBack: '我们什么时候再跟进？',
    pauseTitle: '如果谈话卡住了',
    pauseHint: '可以试试这些问题：',
    pausePrompts: [
      '您能举个例子吗？',
      '在那之前通常会发生什么？',
      '事情进展顺利的时候是什么样子的？',
      '您注意到什么方法有帮助？',
      '我们可以先尝试一个小的支持方法，之后再跟进吗？',
      '成功会是什么样子的？',
    ],
  },

  after: {
    eyebrow: '第四步 · 会后计划',
    title: '把谈话变成计划',
    learned: '您了解到了什么？',
    prioritiesQ: '目前什么最重要？',
    prioritiesHint: '最多选 3 项。',
    prioritiesFull: '您已经选了 3 项。如果想换一个，可以先取消一个。',
    maxPriorities: 3,
    priorities: [
      opt('understanding', '更好地理解情况'),
      opt('overwhelm', '减轻压力感'),
      opt('organization', '提升整理能力'),
      opt('starting', '更独立地开始任务'),
      opt('completing', '完成作业'),
      opt('transitions', '更顺利地转换活动'),
      opt('conflict', '减少作业时的冲突'),
      opt('confidence', '建立自信'),
      opt('communication', '加强与学校的沟通'),
      opt('other', '其他'),
    ],
    willTry: '我们要尝试什么？',
    watchFor: '我们要留意什么？',
    watchForHint: '显示方法有效（或无效）的小迹象。',
    reviewDate: '我们什么时候回顾进展？',
    toSnapshot: '查看我的会谈摘要',
  },

  snapshot: {
    eyebrow: '会谈摘要',
    title: '家长会会谈摘要',
    download: '下载 PDF',
    downloading: '正在生成 PDF…',
    pdfDone: 'PDF 已下载。',
    pdfFailed: '无法在这里生成 PDF（首次使用需要联网）。您可以点击「打印」，然后选择「另存为 PDF」。',
    print: '打印',
    send: '发送',
    sendTitle: '发送或分享',
    shareFile: '分享 PDF…',
    email: '以文字形式发送邮件',
    copy: '复制为文字',
    copied: '已复制。可以粘贴到邮件、微信或备忘录中。',
    copyFailed: '此浏览器无法复制。请尝试「以文字形式发送邮件」。',
    calendar: '将跟进日期加入日历',
    edit: '修改内容',
    backupTitle: '保存或转移您的内容',
    backupHint: '备份文件可以让您在其他设备或浏览器上继续使用。文件中包含您的记录，请妥善保管。',
    exportBtn: '下载备份文件',
    importBtn: '打开备份文件',
    importOk: '已从文件中载入您的内容。',
    importBad: '这不是家长会准备助手的备份文件，内容没有改变。',
    importConfirm: '要用这个文件中的内容替换此浏览器中的内容吗？',
    checkBackEvent: '与老师跟进（家长会后续）',
    reviewEvent: '回顾家长会计划的进展',
    analyticsLabel: '帮助改进此工具：匿名分享我选择的选项。绝不会分享书面记录和日期。',
    analyticsThanks: '谢谢！只会分享匿名的选项选择。',
    reset: '重新开始',
    prepared: '整理日期',
    sections: {
      strengths: '孩子的优势',
      noticing: '我们观察到的情况',
      teacher: '老师看到的情况',
      barriers: '可能的阻碍因素',
      supports: '可能有帮助的支持方法',
      trying: '我们要尝试的方法',
      who: '分工安排',
      followUp: '跟进日期',
      revisit: '之后再跟进的问题',
    },
    labels: {
      engaged: '全情投入的事情',
      teacherStrengths: '老师提到的优势',
      when: '最常出现的场景',
      notProblem: '不成问题的情况',
      patterns: '我们讨论的规律',
      childSays: '孩子自己的话',
      limited: '尝试过，但效果有限或短暂',
      learned: '我了解到的',
      helped: '已经看到帮助的方法',
      agreed: '会上约定',
      plan: '我们的计划',
      priorities: '目前最重要的事',
      watchFor: '我们要留意的',
      checkBack: '与老师跟进',
      review: '回顾进展',
    },
    rememberLabel: '请记住',
    remember: '一次会谈不需要解决所有问题。一次有用的家长会，能让您看得更清楚，带走几个具体的下一步，并知道如何检查这些方法是否有帮助。',
  },
};

window.PTCC = window.PTCC || {};
window.PTCC.content = window.PTCC.content || {};
window.PTCC.content.zh = zh;
})();
